import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListResourcesRequestSchema,
  ListToolsRequestSchema,
  ReadResourceRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { BrowserManager } from "./BrowserManager.js";

const browser = new BrowserManager();

const server = new Server(
  {
    name: "splice-enterprise-browser",
    version: "2.0.0",
  },
  {
    capabilities: {
      resources: {},
      tools: {},
    },
  }
);

// Define Resources
server.setRequestHandler(ListResourcesRequestSchema, async () => {
  return {
    resources: [
      {
        uri: "splice://current-page/semantic-tree",
        name: "Semantic Tree (Raw)",
        mimeType: "application/json",
        description: "The full, raw AI-optimized semantic representation of the current page's DOM structure.",
      },
      {
        uri: "splice://current-page/telemetry",
        name: "Telemetry Data",
        mimeType: "application/json",
        description: "Network and console logs generated by the page.",
      },
      {
        uri: "splice://session/health-dashboard",
        name: "Health & Performance Dashboard",
        mimeType: "application/json",
        description: "Tracks tokens saved, errors prevented, and CAPTCHAs handled in this session.",
      }
    ],
  };
});

server.setRequestHandler(ReadResourceRequestSchema, async (request) => {
  if (request.params.uri === "splice://current-page/semantic-tree") {
    try {
      const tree = await browser.getSemanticTree();
      return {
        contents: [
          {
            uri: request.params.uri,
            mimeType: "application/json",
            text: JSON.stringify(tree, null, 2),
          },
        ],
      };
    } catch (e: any) {
      return {
        contents: [
          {
            uri: request.params.uri,
            mimeType: "application/json",
            text: JSON.stringify({ error: e.message }),
          },
        ],
      };
    }
  }

  if (request.params.uri === "splice://current-page/telemetry") {
    try {
      const logs = browser.getTelemetryLogs();
      return {
        contents: [
          {
            uri: request.params.uri,
            mimeType: "application/json",
            text: JSON.stringify(logs, null, 2),
          },
        ],
      };
    } catch (e: any) {
      return {
        contents: [
          {
            uri: request.params.uri,
            mimeType: "application/json",
            text: JSON.stringify({ error: e.message }),
          },
        ],
      };
    }
  }

  if (request.params.uri === "splice://session/health-dashboard") {
    return {
      contents: [
        {
          uri: request.params.uri,
          mimeType: "application/json",
          text: JSON.stringify(browser.metrics, null, 2),
        },
      ],
    };
  }

  throw new Error(`Resource not found: ${request.params.uri}`);
});

// Define Tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "navigate",
        description: "Navigate the active browser branch to a specific URL.",
        inputSchema: {
          type: "object",
          properties: {
            url: { type: "string", description: "The full URL to navigate to" },
          },
          required: ["url"],
        },
      },
      {
        name: "get_semantic_tree_optimized",
        description: "Extract the Semantic Tree using a specialized lens (UX, Security, Performance) and intent pruning.",
        inputSchema: {
          type: "object",
          properties: {
            intent: { type: "string", description: "Your current goal (e.g. 'checkout', 'login', 'read article'). Used to prune irrelevant DOM elements." },
            lens: { type: "string", enum: ["UX", "Security", "Performance", "Vision"], description: "The Semantic Lens to view the page through." },
            maxTokens: { type: "number", description: "The maximum number of tokens to return. Triggers aggressive truncation if exceeded." }
          },
          required: ["intent"],
        },
      },
      {
        name: "interact",
        description: "Interact with an element using its splice ID (found in the semantic tree). Also handles conflict resolution between agents.",
        inputSchema: {
          type: "object",
          properties: {
            elementId: { type: "string", description: "The data-splice-id of the element (e.g., 'button-1')" },
            action: { type: "string", enum: ["click", "type", "focus", "select", "press"], description: "The action to perform" },
            value: { type: "string", description: "Optional value for 'type', 'select', or 'press' actions" },
            agentId: { type: "string", description: "Optional agent identifier to track conflicts." }
          },
          required: ["elementId", "action"],
        },
      },
      {
        name: "fork_state",
        description: "Clone the current browser state into a new background branch for shadow testing risky actions.",
        inputSchema: {
          type: "object",
          properties: {},
        },
      },
      {
        name: "speculative_fork",
        description: "Proactively fork branches and navigate to a list of URLs in the background to reduce latency when you later navigate to them.",
        inputSchema: {
          type: "object",
          properties: {
            urls: {
              type: "array",
              items: { type: "string" },
              description: "Array of URLs to speculatively pre-load."
            }
          },
          required: ["urls"],
        },
      },
      {
        name: "commit_branch",
        description: "Make a background branch the primary active state.",
        inputSchema: {
          type: "object",
          properties: {
            branchId: { type: "string", description: "The branch ID to commit" },
          },
          required: ["branchId"],
        },
      },
      {
        name: "save_snapshot",
        description: "Serialize the active session (cookies, auth) to the local machine so it can be resumed instantly.",
        inputSchema: {
          type: "object",
          properties: {
            name: { type: "string", description: "Name of the snapshot (e.g., 'auth-github')" },
          },
          required: ["name"],
        },
      },
      {
        name: "load_snapshot",
        description: "Instantly teleport the browser into a previously saved session state.",
        inputSchema: {
          type: "object",
          properties: {
            name: { type: "string", description: "Name of the snapshot to load" },
          },
          required: ["name"],
        },
      },
      {
        name: "request_human_intervention",
        description: "Halt the agent and spawn a visible Chromium window on the host machine to solve a CAPTCHA or unblock a flow.",
        inputSchema: {
          type: "object",
          properties: {
            reason: { type: "string", description: "Why the human is needed (e.g., 'Solve Cloudflare turnstile')" },
          },
          required: ["reason"],
        },
      },
      {
        name: "debug_failure",
        description: "Save a time-travel Playwright trace of the current session to debug hallucination or errors.",
        inputSchema: {
          type: "object",
          properties: {
            sessionId: { type: "string", description: "A unique identifier for this debug trace" },
          },
          required: ["sessionId"],
        },
      },
      {
        name: "capture_node_screenshot",
        description: "Vision Lens: Capture a base64 encoded screenshot of a specific element to pass to a vision model.",
        inputSchema: {
          type: "object",
          properties: {
            elementId: { type: "string", description: "The data-splice-id of the element to capture" },
          },
          required: ["elementId"],
        },
      },
      {
        name: "generate_observability_report",
        description: "Generate a high-aesthetic HTML dashboard containing the latest micro-snapshots, vision logs, and speculative metrics.",
        inputSchema: {
          type: "object",
          properties: {},
        },
      }
    ],
  };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  try {
    if (request.params.name === "navigate") {
      const { url } = request.params.arguments as { url: string };
      await browser.navigate(url);
      return { content: [{ type: "text", text: `Navigated to ${url}.` }] };
    }

    if (request.params.name === "get_semantic_tree_optimized") {
      const { intent, lens, maxTokens } = request.params.arguments as any;
      const tree = await browser.getSemanticTree(intent, lens || "UX", maxTokens);
      return { content: [{ type: "text", text: JSON.stringify(tree, null, 2) }] };
    }

    if (request.params.name === "interact") {
      const { elementId, action, value, agentId } = request.params.arguments as any;
      await browser.interact(elementId, action, value, agentId);
      await new Promise(r => setTimeout(r, 1000)); // wait for network idle/renders
      return { content: [{ type: "text", text: `Successfully performed '${action}' on element '${elementId}'.` }] };
    }

    if (request.params.name === "fork_state") {
      const branchId = await browser.forkState();
      return { content: [{ type: "text", text: `Created new branch: ${branchId}. Switch using commit_branch.` }] };
    }

    if (request.params.name === "speculative_fork") {
      const { urls } = request.params.arguments as { urls: string[] };
      await browser.speculativeFork(urls);
      return { content: [{ type: "text", text: `Speculatively forked and pre-loaded ${urls.length} branches in the background.` }] };
    }

    if (request.params.name === "commit_branch") {
      const { branchId } = request.params.arguments as { branchId: string };
      await browser.commitBranch(branchId);
      return { content: [{ type: "text", text: `Active branch is now ${branchId}.` }] };
    }

    if (request.params.name === "save_snapshot") {
      const { name } = request.params.arguments as { name: string };
      const path = await browser.saveSnapshot(name);
      return { content: [{ type: "text", text: `Snapshot saved to ${path}.` }] };
    }

    if (request.params.name === "load_snapshot") {
      const { name } = request.params.arguments as { name: string };
      await browser.loadSnapshot(name);
      return { content: [{ type: "text", text: `Loaded snapshot ${name}. Session resumed.` }] };
    }

    if (request.params.name === "request_human_intervention") {
      const { reason } = request.params.arguments as { reason: string };
      await browser.requestHumanIntervention(reason);
      return { content: [{ type: "text", text: `Human solved the issue and returned control. Resume your task.` }] };
    }

    if (request.params.name === "debug_failure") {
      const { sessionId } = request.params.arguments as { sessionId: string };
      const tracePath = await browser.debugFailure(sessionId);
      return { content: [{ type: "text", text: `Saved Playwright trace to ${tracePath}. To view it, run 'npx playwright show-trace ${tracePath}' on the host machine.` }] };
    }

    if (request.params.name === "capture_node_screenshot") {
      const { elementId } = request.params.arguments as { elementId: string };
      const base64Str = await browser.captureNodeScreenshot(elementId);
      return { content: [{ type: "text", text: base64Str }] };
    }

    if (request.params.name === "generate_observability_report") {
      const reportPath = await browser.generateObservabilityReport();
      return { content: [{ type: "text", text: `Observability Dashboard generated at: ${reportPath}. Open this file in your browser to visualize the agent's processes.` }] };
    }

    throw new Error(`Tool not found: ${request.params.name}`);
  } catch (error: any) {
    if (error.message.includes("CAPTCHA_REQUIRED")) {
       return {
         content: [{ type: "text", text: "ERROR: CAPTCHA detected. Please call the 'request_human_intervention' tool." }],
         isError: true,
       };
    }
    return {
      content: [{ type: "text", text: `Error executing tool: ${error.message}` }],
      isError: true,
    };
  }
});

async function main() {
  await browser.init();
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("Splice Enterprise MCP Server is running...");
}

main().catch((error) => {
  console.error("Fatal error running server:", error);
});
